apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd

spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sshd
  template:
    metadata:
      labels:
        app: sshd
    spec:
      volumes:
        - name: sshd-pvc
          persistentVolumeClaim:
            claimName: sshd-pvc
      containers:
        - name: sshd
          image: localhost:5001/flux_sshd:v1
          ports:
            - containerPort: 2220
          volumeMounts:
            - mountPath: "/home/logit/git"
              name: sshd-pvc
