---
apiVersion: v1
kind: Secret
metadata:
  name: flux-system
  namespace: flux-system
stringData:
  identity: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAYEAsjUgKMAku/Fl5M3NHAeVB0Dv9wTvJsKeWMnpi/hhLCMrqKL1IPQl
    4w3JlDJmHAouwdtV4o5y+ecccwz8fj0zYGZUJBeVtIEUOgtUGstKa0Wsg+yku+W2bsuU30
    yInKAmkTxekvueVnNGmuCGWiysNsa/NDmqStoZ83Xj/q2+FCRmeQ70EMwOQXbC9CdzdD/8
    aqG2tZOH9F6jZ/htyoBD4ETJHoErwjc9BK8SMqt0GRtf6r4y7D0m0jrKBC5XWZUm59o9cs
    4dsgSv0Ixlzk1GQbHbjoA0AxWwBDX3TUOq+UBrqF0F30P8XCc7HIRcPHGNmKyFf7sUHFqQ
    y4ySrs0pdVoqsM9aOB9+/VrlW8dGybiuKxaxFbtpHbqfTGZg19iDXaAccDxi2vjxJM70sh
    xN3J1OhsGPqeS9zgDvM473LKd/SM9H7m3wTuaesBZpMGb8RT/hM+0tVK6xDm6NumfBBWbk
    2cWEZAN1PERg6XwpvEMItfUuq16YyelZ05nb6lvTAAAFmLluQeq5bkHqAAAAB3NzaC1yc2
    EAAAGBALI1ICjAJLvxZeTNzRwHlQdA7/cE7ybCnljJ6Yv4YSwjK6ii9SD0JeMNyZQyZhwK
    LsHbVeKOcvnnHHMM/H49M2BmVCQXlbSBFDoLVBrLSmtFrIPspLvltm7LlN9MiJygJpE8Xp
    L7nlZzRprghlosrDbGvzQ5qkraGfN14/6tvhQkZnkO9BDMDkF2wvQnc3Q//GqhtrWTh/Re
    o2f4bcqAQ+BEyR6BK8I3PQSvEjKrdBkbX+q+Muw9JtI6ygQuV1mVJufaPXLOHbIEr9CMZc
    5NRkGx246ANAMVsAQ1901DqvlAa6hdBd9D/FwnOxyEXDxxjZishX+7FBxakMuMkq7NKXVa
    KrDPWjgffv1a5VvHRsm4risWsRW7aR26n0xmYNfYg12gHHA8Ytr48STO9LIcTdydTobBj6
    nkvc4A7zOO9yynf0jPR+5t8E7mnrAWaTBm/EU/4TPtLVSusQ5ujbpnwQVm5NnFhGQDdTxE
    YOl8KbxDCLX1LqtemMnpWdOZ2+pb0wAAAAMBAAEAAAGAGcJGGL3VUXlOMilxSWjrKLZBOW
    J0MxUUkF73LC1F1nxq9iA/8Hh59Xzrs0kpq0npgkny+yF+CxNV8GdjI9gy0e9YoDLsh7/U
    raMvkAPsiN70Vclh8mr82L0CkthcMs+PY5TnUrWeKH7XKNHlealVZ0GJJ8JiFBm8gI183D
    Y+8Ghmi38W1kq4kMva2DHPpXEOSld/snVVxIPdeMzXCdtKdGNc8tTW/2a+oiuwJLTVvj9P
    uP2vHKimMOMgikQsih1d2WXxhYupfderKdlvwBSzDzXCdK+7eF38tz4JB6l8pTp8oxnkyH
    LmFDcPK+p/19VFvnNNXwpbovpflwsE2prwFzeC+F1wyz27BYq5Oq9OgMrqUec9Y/x0eOzm
    XfREdnKu6I/WAjALa2CNK0xtk52yv6btajdDnIK/3saPAAOJxv5MIkLcGPpOx63+tNWhiT
    x7avd2pcxoB+bzD3smFfdtdBAuMuJs7WUZTJq4GnSMhUjUsqErj2PRacv3xQmFUrCZAAAA
    wQDBz3dPHxl2JoQC859+yL/sZBZFt/KxWb3EDVm0Y570wnw/ajlvfYQYdt+DivoWusOz9i
    +YM0obqIItLFf1Xm1oIDwMab1qXVPCm/Eo7xF20+Wq0nfFsTcfxv+TCpDZVXaVAOQsErtI
    cwLka/b3yjtICkRjUKTnU3FLf85UYfCQb/tWh9+xaYgN3vs1nCozTRhksTXkG2WFMyhKEc
    ZKivlgtDrQZTsgwHH5YSUkNVWNc7D0B4k0ujSjsi9A4qj9t3MAAADBAOT50bEfvAXlUKjL
    wcYgPRa8XH95tPgQK9arm/xaYo4+OICwTX8fcbKM1wa6APU3YvzWnappAu63Vwys4S3RDR
    l9UOCrd2O7gPQXiOGsLdYYgtBEQJysJZIlR8Pbw4+1DU7ERnCyeTS5VUucnlYq3z8vEk/D
    w4A1Uj8k1Nqfpgs2WDfpFqxXJtrHqWFsLz+p1n4AxilSdfn0oiSH7cXZTJt/5H2v9b2d0b
    xQ1+7nY+xUWJflMFurSS9lDOVV1aSAVwAAAMEAxz1pzDBJJdXI4wp0X9SHIUMeaH9RLirq
    YIqzXnajVcOWpGB895hFnNgMt3U8pp6SmvFJMS7dAzWZpKTWZul/1KT8n57lUxDU87tT5j
    cP+hmj1VyNTTQcyEUEp3eNEzG4ZVDjpQ9zIxLsTa6ETI8Uzd3eydKJVpAI59a7Lghtkp4C
    YQ2VfsY8AmjHIKkipi29WELtLKBXhLIkJJ5mokfv9HcWVB9Kf/fLLefJlsNj2qbG8L8a3F
    ndwtqE86K8CCLlAAAAHUtleSB1c2VkIGZvciBsb2dpdCBTU0ggc2VydmVyAQIDBAU=
    -----END OPENSSH PRIVATE KEY-----
  identity.pub: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCyNSAowCS78WXkzc0cB5UHQO/3BO8mwp5YyemL+GEsIyuoovUg9CXjDcmUMmYcCi7B21XijnL55xxzDPx+PTNgZlQkF5W0gRQ6C1Qay0prRayD7KS75bZuy5TfTIicoCaRPF6S+55Wc0aa4IZaLKw2xr80OapK2hnzdeP+rb4UJGZ5DvQQzA5BdsL0J3N0P/xqoba1k4f0XqNn+G3KgEPgRMkegSvCNz0ErxIyq3QZG1/qvjLsPSbSOsoELldZlSbn2j1yzh2yBK/QjGXOTUZBsduOgDQDFbAENfdNQ6r5QGuoXQXfQ/xcJzschFw8cY2YrIV/uxQcWpDLjJKuzSl1Wiqwz1o4H379WuVbx0bJuK4rFrEVu2kdup9MZmDX2INdoBxwPGLa+PEkzvSyHE3cnU6GwY+p5L3OAO8zjvcsp39Iz0fubfBO5p6wFmkwZvxFP+Ez7S1UrrEObo26Z8EFZuTZxYRkA3U8RGDpfCm8Qwi19S6rXpjJ6VnTmdvqW9M=
  known_hosts: "sshd.management ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKnplEF32qTm13+lFTH81NrvV5iNMLykqiNnfubGeDBStlld5MhDUKToJRQj8sZ/jVWOk6M/axNTdOSJdiVFrfU="
