apiVersion: apps/v1
kind: Deployment
metadata:
  name: logit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logit-app
  template:
    metadata:
      labels:
        app: logit-app
    spec:
      containers:
      - name: logit-app
        image: logit:v2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: logit-app-service
spec:
  selector:
    app: logit-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

